apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: hellogopher
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        imagePullPolicy: IfNotPresent
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: password
        ports:
          - containerPort: 3306
            name: mysql
---

apiVersion: v1 
kind: Service
metadata:
  name: mysql 
  namespace: hellogopher 
spec:
  ports: 
  - port: 3306
  selector:
    app: mysql